
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_oauth2
    username: root
    password: abcd1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # 개발용 only
    show-sql: true

security:
  oauth2:
    jwt:
      signkey: 123@#$

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
